// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }









// // app/layout.tsx
// import './globals.css'; // Ensure this is correctly imported
// import type { Metadata } from "next";



// export const metadata: Metadata = {
//   title: "MyResearchPaper",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body>
//         <div className="min-h-screen flex flex-col">
//           {children}
//         </div>
//       </body>
//     </html>
//   );
// }









// app/layout.tsx
import './globals.css'; // Ensure this is correctly imported
import type { Metadata } from "next";
import { ThemeProvider } from './components/common/themeContext';

export const metadata: Metadata = {
  title: "MyResearchPaper - AI-Powered Research Paper Generator",
  description: "Generate professional research papers with AI assistance. MyResearchPaper helps you create high-quality papers quickly and efficiently.",
  keywords: [
    "research paper generator",
    "AI research paper",
    "academic writing",
    "research paper writing",
    "AI writing tool",
    "MyResearchPaper",
  ],
  authors: [
    {
      name: "MyResearchPaper Team",
      url: "https://myresearchpaper.in",
    },
  ],
  openGraph: {
    title: "MyResearchPaper - AI-Powered Research Paper Generator",
    description: "Generate professional research papers with AI assistance. MyResearchPaper helps you create high-quality papers quickly and efficiently.",
    url: "https://myresearchpaper.in",
    siteName: "MyResearchPaper",
    images: [
      {
        url: "https://myresearchpaper.in/og-image.png", // Replace with your OG image URL
        width: 1200,
        height: 630,
        alt: "MyResearchPaper - AI-Powered Research Paper Generator",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "MyResearchPaper - AI-Powered Research Paper Generator",
    description: "Generate professional research papers with AI assistance. MyResearchPaper helps you create high-quality papers quickly and efficiently.",
    images: ["https://myresearchpaper.in/og-image.png"], // Replace with your OG image URL
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  icons: {
    icon: "/favicon.ico", // Path to your favicon
    shortcut: "/favicon-16x16.png", // Path to your shortcut icon
    apple: "/apple-touch-icon.png", // Path to your Apple touch icon
  },
  manifest: "/site.webmanifest", // Path to your web manifest
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen flex flex-col">
          <ThemeProvider>
            {children}
          </ThemeProvider>
        </div>
      </body>
    </html>
  );
}