// import React from 'react';

// const Terms = () => {
//   return (
//     <div className="max-w-4xl mx-auto p-6 bg-gray-100 rounded-lg">
//       <h1 className="text-3xl font-semibold text-center mb-6">Terms & Conditions</h1>

//       <p className="text-lg mb-4">
//         This document is an electronic record in terms of the Information Technology Act, 2000 and rules thereunder as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
//       </p>

//       <p className="text-lg mb-4">
//         This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy, and Terms of Use for access or usage of domain name https://www.myresearchpaper.in (&apos;Website&apos;), including the related mobile site and mobile application (hereinafter referred to as &apos;Platform&apos;).
//       </p>

//       <p className="text-lg mb-4">
//         The Platform is owned by My Research Paper, a company incorporated under the Companies Act, 1956 with its registered office at Shri Krishna Nagar, Aurangabad, India (hereinafter referred to as &apos;Platform Owner&apos;, &apos;we&apos;, &apos;us&apos;, &apos;our&apos;).
//       </p>

//       <p className="text-lg mb-4">
//         Your use of the Platform and services and tools are governed by the following terms and conditions (&quot;Terms of Use&quot;) as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If you transact on the Platform, you shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, you shall be contracting with the Platform Owner and these terms and conditions including the policies constitute your binding obligations with the Platform Owner. These Terms of Use relate to your use of our website, goods (as applicable) or services (as applicable) (collectively, &apos;Services&apos;). Any terms and conditions proposed by you which are in addition to or which conflict with these Terms of Use are expressly rejected by the Platform Owner and shall be of no force or effect. These Terms of Use can be modified at any time without assigning any reason. It is your responsibility to periodically review these Terms of Use to stay informed of updates.
//       </p>

//       <p className="text-lg mb-4">
//         For the purpose of these Terms of Use, wherever the context so requires, &apos;you&apos;, &apos;your&apos; or &apos;user&apos; shall mean any natural or legal person who has agreed to become a user/buyer on the Platform.
//       </p>

//       <p className="text-lg mb-4">
//         ACCESSING, BROWSING, OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.
//       </p>

//       <h2 className="text-2xl font-semibold mt-6 mb-4">The use of Platform and/or availing of our Services is subject to the following Terms of Use:</h2>

//       <h3 className="text-xl font-semibold mt-4">1. Use of Services</h3>
//       <p className="text-lg mb-4">
//         To access and use the Services, you agree to provide true, accurate, and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.
//       </p>

//       <h3 className="text-xl font-semibold mt-4">2. No Returns or Refunds</h3>
//       <p className="text-lg mb-4">
//         Due to the nature of the services provided (digital products or downloadable content), no returns or refunds will be accepted after the purchase has been completed. Once a product or service has been accessed or downloaded, it cannot be returned or refunded.
//       </p>
//       <p className="text-lg mb-4">
//         Refunds: We do not offer any refunds once the payment has been processed and the digital product (e.g., PDF) has been delivered or downloaded.
//       </p>
//       <p className="text-lg mb-4">
//         Cancellations: Since the products offered are digital downloads, cancellations are not accepted after the transaction is completed. By using our services, you acknowledge and agree to these terms. In case of issues with payment or access to the service, please contact us immediately to resolve the problem.
//       </p>

//       <h3 className="text-xl font-semibold mt-4">3. Warranty Disclaimer</h3>
//       <p className="text-lg mb-4">
//         Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness, or suitability of the information and materials offered on this website or through the Services, for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors, and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.
//       </p>

//       <h3 className="text-xl font-semibold mt-4">4. Liability</h3>
//       <p className="text-lg mb-4">
//         Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner. You are required to independently assess and ensure that the Services meet your requirements.
//       </p>

//       <h3 className="text-xl font-semibold mt-4">5. Proprietary Rights</h3>
//       <p className="text-lg mb-4">
//         The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents. The contents include and are not limited to the design, layout, look, and graphics.
//       </p>

//       <h3 className="text-xl font-semibold mt-4">6. User Agreement</h3>
//       <p className="text-lg mb-4">
//         You agree not to use the Platform and/or Services for any unlawful, illegal, or forbidden purpose by these Terms or Indian or local laws that might apply to you.
//       </p>

//       <p className="text-lg mb-4">
//         You agree and acknowledge that the website and the Services may contain links to other third-party websites. On accessing these links, you will be governed by the terms of use, privacy policy, and other policies of such third-party websites.
//       </p>

//       <h3 className="text-xl font-semibold mt-4">7. Indemnification</h3>
//       <p className="text-lg mb-4">
//         You shall indemnify and hold harmless Platform Owner, its affiliates, group companies (as applicable), and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorney&apos;s fees, made by any third party or penalty imposed due to or arising out of your breach of these Terms of Use, Privacy Policy, and other Policies, or your violation of any law, rules, or regulations or the rights (including infringement of intellectual property rights) of a third party.
//       </p>

//       <h3 className="text-xl font-semibold mt-4">8. Governing Law</h3>
//       <p className="text-lg mb-4">
//         These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the laws of India.
//       </p>

//       <h3 className="text-xl font-semibold mt-4">9. Jurisdiction</h3>
//       <p className="text-lg mb-4">
//         All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in Aurangabad and Bihar.
//       </p>
//     </div>
//   );
// };

// export default Terms;




















// import React from 'react';

// const Terms = () => {
//   return (
//     <div className="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100 dark:from-gray-900 dark:to-gray-800 pt-20 pb-12">
//       <div className="max-w-4xl mx-auto p-8 bg-white/80 dark:bg-gray-900/80 backdrop-blur-xl rounded-2xl shadow-xl">
//         {/* Header Section */}
//         <div className="text-center mb-12">
//           <h1 className="text-4xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-indigo-600 to-purple-600 dark:from-indigo-400 dark:to-purple-400 mb-4">
//             Terms & Conditions
//           </h1>
//           <p className="text-gray-600 dark:text-gray-400">
//             Last updated: January 2024
//           </p>
//         </div>

//         {/* Main Content */}
//         <div className="space-y-8 text-gray-700 dark:text-gray-300">
//           {/* Introduction Section */}
//           <div className="prose dark:prose-invert max-w-none">
//             <p className="leading-relaxed">
//               This document is an electronic record in terms of the Information Technology Act, 2000 and rules thereunder as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
//             </p>
//           </div>

//           {/* Platform Information */}
//           <div className="p-6 bg-indigo-50 dark:bg-indigo-900/20 rounded-xl">
//             <p className="leading-relaxed">
//               This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy, and Terms of Use for access or usage of domain name <span className="text-indigo-600 dark:text-indigo-400">https://www.myresearchpaper.in</span> ('Website'), including the related mobile site and mobile application (hereinafter referred to as 'Platform').
//             </p>
//           </div>

//           {/* Terms Sections */}
//           <div className="space-y-12">
//             {/* Section 1 */}
//             <section className="space-y-4">
//               <div className="flex items-center space-x-3">
//                 <div className="flex-shrink-0 w-8 h-8 bg-indigo-100 dark:bg-indigo-900/50 rounded-full flex items-center justify-center">
//                   <span className="text-indigo-600 dark:text-indigo-400 font-semibold">1</span>
//                 </div>
//                 <h2 className="text-2xl font-bold text-gray-900 dark:text-white">Use of Services</h2>
//               </div>
//               <div className="ml-11">
//                 <p className="leading-relaxed">
//                   To access and use the Services, you agree to provide true, accurate, and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.
//                 </p>
//               </div>
//             </section>

//             {/* Section 2 */}
//             <section className="space-y-4">
//               <div className="flex items-center space-x-3">
//                 <div className="flex-shrink-0 w-8 h-8 bg-indigo-100 dark:bg-indigo-900/50 rounded-full flex items-center justify-center">
//                   <span className="text-indigo-600 dark:text-indigo-400 font-semibold">2</span>
//                 </div>
//                 <h2 className="text-2xl font-bold text-gray-900 dark:text-white">No Returns or Refunds</h2>
//               </div>
//               <div className="ml-11 space-y-4">
//                 <p className="leading-relaxed">
//                   Due to the nature of the services provided (digital products or downloadable content), no returns or refunds will be accepted after the purchase has been completed.
//                 </p>
//                 <div className="bg-gray-50 dark:bg-gray-800/50 p-4 rounded-lg">
//                   <p className="font-medium mb-2">Important Note:</p>
//                   <ul className="list-disc list-inside space-y-2 text-gray-600 dark:text-gray-400">
//                     <li>We do not offer any refunds once the payment has been processed</li>
//                     <li>Cancellations are not accepted after transaction completion</li>
//                     <li>Contact us immediately for payment or access issues</li>
//                   </ul>
//                 </div>
//               </div>
//             </section>

//             {/* Continue with other sections in the same format... */}
//           </div>

//           {/* Footer Section */}
//           <div className="mt-12 pt-8 border-t border-gray-200 dark:border-gray-700">
//             <div className="flex items-center justify-between text-sm text-gray-500 dark:text-gray-400">
//               <p>© 2024 MyResearchPaper. All rights reserved.</p>
//               <p>Courts of Aurangabad and Bihar</p>
//             </div>
//           </div>
//         </div>
//       </div>
//     </div>
//   );
// };

// export default Terms;


















import React from 'react';
import Link from 'next/link'; // Import Link from Next.js

const Terms = () => {
  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100 dark:from-gray-900 dark:to-gray-800 pt-20 pb-12">
      <div className="max-w-4xl mx-auto p-8 bg-white/80 dark:bg-gray-900/80 backdrop-blur-xl rounded-2xl shadow-xl">
        {/* Header Section */}
        <div className="text-center mb-12">
          <h1 className="text-4xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-indigo-600 to-purple-600 dark:from-indigo-400 dark:to-purple-400 mb-4">
            Terms & Conditions
          </h1>
          <p className="text-gray-600 dark:text-gray-400">
            Last updated: January 2024
          </p>
        </div>

        {/* Main Content */}
        <div className="space-y-8 text-gray-700 dark:text-gray-300">
          {/* Introduction Section */}
          <div className="prose dark:prose-invert max-w-none">
            <p className="leading-relaxed">
              This document is an electronic record in terms of the Information Technology Act, 2000 and rules thereunder as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
            </p>
          </div>

          {/* Platform Information */}
          <div className="p-6 bg-indigo-50 dark:bg-indigo-900/20 rounded-xl">
            <p className="leading-relaxed">
              This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy, and Terms of Use for access or usage of domain name <span className="text-indigo-600 dark:text-indigo-400">https://www.myresearchpaper.in</span> (&apos;Website&apos;), including the related mobile site and mobile application (hereinafter referred to as &apos;Platform&apos;).
            </p>
          </div>

          {/* Terms Sections */}
          <div className="space-y-12">
            {/* Section 1 */}
            <section className="space-y-4">
              <div className="flex items-center space-x-3">
                <div className="flex-shrink-0 w-8 h-8 bg-indigo-100 dark:bg-indigo-900/50 rounded-full flex items-center justify-center">
                  <span className="text-indigo-600 dark:text-indigo-400 font-semibold">1</span>
                </div>
                <h2 className="text-2xl font-bold text-gray-900 dark:text-white">Use of Services</h2>
              </div>
              <div className="ml-11">
                <p className="leading-relaxed">
                  To access and use the Services, you agree to provide true, accurate, and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.
                </p>
              </div>
            </section>

            {/* Section 2 */}
            <section className="space-y-4">
              <div className="flex items-center space-x-3">
                <div className="flex-shrink-0 w-8 h-8 bg-indigo-100 dark:bg-indigo-900/50 rounded-full flex items-center justify-center">
                  <span className="text-indigo-600 dark:text-indigo-400 font-semibold">2</span>
                </div>
                <h2 className="text-2xl font-bold text-gray-900 dark:text-white">No Returns or Refunds</h2>
              </div>
              <div className="ml-11 space-y-4">
                <p className="leading-relaxed">
                  Due to the nature of the services provided (digital products or downloadable content), no returns or refunds will be accepted after the purchase has been completed.
                </p>
                <div className="bg-gray-50 dark:bg-gray-800/50 p-4 rounded-lg">
                  <p className="font-medium mb-2">Important Note:</p>
                  <ul className="list-disc list-inside space-y-2 text-gray-600 dark:text-gray-400">
                    <li>We do not offer any refunds once the payment has been processed</li>
                    <li>Cancellations are not accepted after transaction completion</li>
                    <li>Contact us immediately for payment or access issues</li>
                  </ul>
                </div>
              </div>
            </section>

            {/* Privacy Policy Section */}
            <section className="space-y-4">
              <div className="flex items-center space-x-3">
                <div className="flex-shrink-0 w-8 h-8 bg-indigo-100 dark:bg-indigo-900/50 rounded-full flex items-center justify-center">
                  <span className="text-indigo-600 dark:text-indigo-400 font-semibold">3</span>
                </div>
                <h2 className="text-2xl font-bold text-gray-900 dark:text-white">Privacy Policy</h2>
              </div>
              <div className="ml-11">
                <p className="leading-relaxed">
                  Your privacy is important to us. Please note that we do not collect any user data or information through our platform. We are committed to maintaining the privacy and confidentiality of your actions on the site.
                </p>
                <div className="bg-gray-50 dark:bg-gray-800/50 p-4 rounded-lg">
                  <p className="font-medium mb-2">Key Points:</p>
                  <ul className="list-disc list-inside space-y-2 text-gray-600 dark:text-gray-400">
                    <li>We do not collect any personal data from users.</li>
                    <li>We do not track user activity or gather any data beyond what is necessary for the platform to function.</li>
                    <li>Your privacy is respected, and we do not share any information with third parties.</li>
                  </ul>
                </div>
              </div>
            </section>

            {/* Back to Home Page Button */}
            <div className="mt-8 text-center">
              <Link href="/">
                <button className="px-6 py-3 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition duration-300">
                  Back to Home Page
                </button>
              </Link>
            </div>

            {/* Footer Section */}
            <div className="mt-12 pt-8 border-t border-gray-200 dark:border-gray-700">
              <div className="flex items-center justify-between text-sm text-gray-500 dark:text-gray-400">
                <p>© 2024 MyResearchPaper. All rights reserved.</p>
                <p>Courts of Aurangabad and Bihar</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Terms;
