import React from 'react';
import Link from 'next/link'; 

const Terms = () => {
  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100 dark:from-gray-900 dark:to-gray-800 pt-20 pb-12">
      <div className="max-w-4xl mx-auto p-8 bg-white/80 dark:bg-gray-900/80 backdrop-blur-xl rounded-2xl shadow-xl">
       
        <div className="text-center mb-12">
          <h1 className="text-4xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-indigo-600 to-purple-600 dark:from-indigo-400 dark:to-purple-400 mb-4">
            Terms & Conditions
          </h1>
          <p className="text-gray-600 dark:text-gray-400">
            Last updated: January 2024
          </p>
        </div>

        <div className="space-y-8 text-gray-700 dark:text-gray-300">
         
          <div className="prose dark:prose-invert max-w-none">
            <p className="leading-relaxed">
              This document is an electronic record in terms of the Information Technology Act, 2000 and rules thereunder as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
            </p>
          </div>


          <div className="p-6 bg-indigo-50 dark:bg-indigo-900/20 rounded-xl">
            <p className="leading-relaxed">
              This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy, and Terms of Use for access or usage of domain name <span className="text-indigo-600 dark:text-indigo-400">https://www.myresearchpaper.in</span> (&apos;Website&apos;), including the related mobile site and mobile application (hereinafter referred to as &apos;Platform&apos;).
            </p>
          </div>

          
          <div className="space-y-12">
            <section className="space-y-4">
              <div className="flex items-center space-x-3">
                <div className="flex-shrink-0 w-8 h-8 bg-indigo-100 dark:bg-indigo-900/50 rounded-full flex items-center justify-center">
                  <span className="text-indigo-600 dark:text-indigo-400 font-semibold">1</span>
                </div>
                <h2 className="text-2xl font-bold text-gray-900 dark:text-white">Use of Services</h2>
              </div>
              <div className="ml-11">
                <p className="leading-relaxed">
                  To access and use the Services, you agree to provide true, accurate, and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.
                </p>
              </div>
            </section>

            <section className="space-y-4">
              <div className="flex items-center space-x-3">
                <div className="flex-shrink-0 w-8 h-8 bg-indigo-100 dark:bg-indigo-900/50 rounded-full flex items-center justify-center">
                  <span className="text-indigo-600 dark:text-indigo-400 font-semibold">2</span>
                </div>
                <h2 className="text-2xl font-bold text-gray-900 dark:text-white">No Returns or Refunds</h2>
              </div>
              <div className="ml-11 space-y-4">
                <p className="leading-relaxed">
                  Due to the nature of the services provided (digital products or downloadable content), no returns or refunds will be accepted after the purchase has been completed.
                </p>
                <div className="bg-gray-50 dark:bg-gray-800/50 p-4 rounded-lg">
                  <p className="font-medium mb-2">Important Note:</p>
                  <ul className="list-disc list-inside space-y-2 text-gray-600 dark:text-gray-400">
                    <li>We do not offer any refunds once the payment has been processed</li>
                    <li>Cancellations are not accepted after transaction completion</li>
                    <li>Contact us immediately for payment or access issues</li>
                  </ul>
                </div>
              </div>
            </section>

            {/* Privacy Policy Section */}
            <section className="space-y-4">
              <div className="flex items-center space-x-3">
                <div className="flex-shrink-0 w-8 h-8 bg-indigo-100 dark:bg-indigo-900/50 rounded-full flex items-center justify-center">
                  <span className="text-indigo-600 dark:text-indigo-400 font-semibold">3</span>
                </div>
                <h2 className="text-2xl font-bold text-gray-900 dark:text-white">Privacy Policy</h2>
              </div>
              <div className="ml-11">
                <p className="leading-relaxed">
                  Your privacy is important to us. Please note that we do not collect any user data or information through our platform. We are committed to maintaining the privacy and confidentiality of your actions on the site.
                </p>
                <div className="bg-gray-50 dark:bg-gray-800/50 p-4 rounded-lg">
                  <p className="font-medium mb-2">Key Points:</p>
                  <ul className="list-disc list-inside space-y-2 text-gray-600 dark:text-gray-400">
                    <li>We do not collect any personal data from users.</li>
                    <li>We do not track user activity or gather any data beyond what is necessary for the platform to function.</li>
                    <li>Your privacy is respected, and we do not share any information with third parties.</li>
                  </ul>
                </div>
              </div>
            </section>

            <div className="mt-8 text-center">
              <Link href="/">
                <button className="px-6 py-3 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition duration-300">
                  Back to Home Page
                </button>
              </Link>
            </div>

            <div className="mt-12 pt-8 border-t border-gray-200 dark:border-gray-700">
              <div className="flex items-center justify-between text-sm text-gray-500 dark:text-gray-400">
                <p>© 2024 MyResearchPaper. All rights reserved.</p>
                <p>Courts of Aurangabad and Bihar</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Terms;
